---
title: "convergence_10_2"
output: html_document
---

```{r, include=FALSE}
library(tidyverse)
library(haven)
library(ConvergenceClubs)
library(sandwich)
library(lmtest)
library(broom)

panel = read_dta("https://www.dropbox.com/scl/fi/hb2rsfjqlu438c3hcd2ct/country_gdp_inequality_and_more.dta?rlkey=ewxox10esprcfkajrg189ilca&st=7dzzp9l4&dl=1")

.add_indicator = function(df, measure){
 
  key = tolower(gsub("[^a-z0-9]", "", measure))
  
  if (key == "shwealthtop1") {
    df = df |> mutate(val = .data[["sh_wealth_top1"]])
  } else if (key == "shincometop1") {
    df = df |> mutate(val = .data[["sh_income_top1"]])
  } else if (key == "shwealthtop10") {
    df = df |> mutate(val = .data[["sh_wealth_top10"]])
  } else if (key == "shincometop10") {
    df = df |> mutate(val = .data[["sh_income_top10"]])
  } else if (key == "pipgini") {
    df = df |> mutate(val = .data[["pip_gini"]])
  } else {
    stop("`measure` not recognized. Use one of: 'sh_wealth_top1', 'sh_income_top1',
         'sh_wealth_top10', 'sh_income_top10', 'pip_gini'")
  }
  
  df |> select(code, year, val)
}


# Function to build balanced panel with relevant indicators
make_panel = function(data, measure = "sh_wealth_top1"){
  
  df = data |> .add_indicator(measure)
  
  wide = df |>
    pivot_wider(names_from = "year", values_from = "val") |>
    arrange(code) |>
    as.data.frame()
  
  wide
}

# Function to run Phillips-Sul tests
run_ps = function(data,
                  measure = "sh_wealth_top1",
                  dataCols,
                  time_trim = 0.3,
                  HACmethod = "FQSB",
                  cstar = 0,
                  refCol = NULL) {
  
  panel_df = make_panel(data, measure)
  
  if(is.null(refCol)) {
    refCol = max(dataCols)
  }
  
  H = computeH(panel_df[, dataCols], quantity = "H")
  global = estimateMod(H, time_trim = time_trim, HACmethod = HACmethod)
  
  clubs = findClubs(panel_df, dataCols = dataCols, unit_names = 1, refCol = refCol,
                    time_trim = time_trim, cstar = cstar, HACmethod = HACmethod)
  
  list(H = H, global = global, clubs = clubs)
}
```

Using Durlauf-Johnson (1995) growth regimes:

```{r}
# Column 1
group1 = c(
  "BFA","BDI","ETH","MWI","MLI","MRT","NER","RWA","SLE","TZA",
  "TGO","UGA","COD","MMR")
panel1 = panel |> filter(code %in% group1) |> filter(year %in% 1995:2022)

# Column 2
group2 = c(
  "DZA","AGO","BEN","CMR","CAF","TCD","COG","EGY","GHA","CIV",
  "KEN","LBR","MAR","MOZ","NGA","SEN","SOM","SDN","TUN","ZMB",
  "ZWE","BGD","IND","JOR","NPL","PAK","SYR","TUR","GTM","HTI",
  "HND","BOL","IDN","PNG")
panel2 = panel |> filter(code %in% group2) |> filter(year %in% 1995:2022)

# Column 3
group3 = c(
  "MDG","ZAF","HKG","ISR","JPN","KOR","MYS","PHL","SGP","LKA",
  "THA","GRC","IRL","PRT","ESP","CRI","DOM","SLV","JAM","MEX",
  "NIC","PAN","BRA","COL","ECU","PRY","PER")
panel3 = panel |> filter(code %in% group3) |> filter(year %in% 1995:2022)


# Column 4
group4 = c(
  "AUT","BEL","DNK","FIN","FRA","DEU","ITA","NLD","NOR","SWE",
  "CHE","GBR","CAN","TTO","USA","ARG","CHL","URY","VEN","AUS","NZL")
panel4 = panel |> filter(code %in% group4) |> filter(year %in% 1995:2022)
```






